###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        container_name: myapp-mysql
        image: 'mysql:8.0'
        working_dir: /var/www/myapp
        volumes:
            - './cakephp:/var/www/myapp'
        environment:
            - MYSQL_ROOT_PASSWORD=tyrelldb123!
            - MYSQL_DATABASE=tyrell_db
            - MYSQL_USER=tyrell_db
            - MYSQL_PASSWORD=tyrell123
        ports:
            - '8003:3306'

    webserver:
        container_name: myapp-nginx
        image: 'nginx:alpine'
        working_dir: /var/www/myapp
        volumes:
            - './cakephp:/var/www/myapp'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8001:80'

    php-fpm:
        container_name: myapp-php-fpm
        build: phpdocker/php-fpm
        working_dir: /var/www/myapp
        volumes:
            - './cakephp:/var/www/myapp'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
